(in-package :cl-aubio/examples)

(defun filterbank-example ()
  (let* ((samplerate 48000)
         (window-size 2048)
         (frequencies #(60.0 80.0 200.0 400.0 800.0 1600.0 3200.0 6400.0 12800.0 24000.0))
         (number-of-filters (- (length frequencies) 2))
         (filterbank (aubio:make-filterbank number-of-filters window-size))
         (frequencies-as-aubio-vector (aubio:make-float-vector-from-lisp-vector frequencies)))
    (setf (aubio:triangle-bands filterbank (float samplerate)) frequencies-as-aubio-vector)
    (setf (aubio:filter-coefficients filterbank) (aubio:weight-matrix-row (aubio:filter-coefficients filterbank) 4 6.0))
    (display-plot (transpose (frequency-list number-of-filters samplerate window-size))
                  (transpose (aubio:aubio-to-lisp (aubio:filter-coefficients filterbank)))
                  samplerate)
    (aubio:clean frequencies-as-aubio-vector)
    (aubio:clean filterbank)))

(defun transpose (array)
  "Transposes a 2D array but in the form of list of lists (so vgplot can render them in a plot)"
  (declare (type (array float (* *)) array))
  (destructuring-bind (height width) (array-dimensions array)
    (loop :for i :below width :collecting
                              (loop :for j :below height :collecting (row-major-aref array (array-row-major-index array j i))))))
(defun frequency-list (number-of-filters samplerate window-size)
  (let ((index-stop (1+ (floor (/ window-size 2)))))
    (make-array '(8 1025) :initial-contents (loop :for i :below number-of-filters
                                                  :collecting (map 'vector (lambda (item) (/ (* item samplerate) window-size))
                                                                           (vgplot:range index-stop))))))

(defun display-plot (x-values y-values samplerate)
  (vgplot:loglog (mapcar #'first x-values) (mapcar #'first y-values)
                 (mapcar #'second x-values) (mapcar #'second y-values)
                 (mapcar #'third x-values) (mapcar #'third y-values)
                 (mapcar #'fourth x-values) (mapcar #'fourth y-values)
                 (mapcar #'fifth x-values) (mapcar #'fifth y-values)
                 (mapcar #'sixth x-values) (mapcar #'sixth y-values)
                 (mapcar #'seventh x-values) (mapcar #'seventh y-values)
                 (mapcar #'eighth x-values) (mapcar #'eighth y-values))
  (vgplot:title "filterbank built from a list of frequencies. The 5th band has been amplified by a factor 6.")
  (vgplot:axis '(50 (/ samplerate 2) 1.0e-6 2.0e-2))
  (vgplot:xlabel "log frequency (Hz)")
  (vgplot:ylabel "log amplitude"))
